// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// merge_relationship_periods
DataFrame merge_relationship_periods(DataFrame dtable, std::string id_column, std::string from_column, std::string to_column, CharacterVector characteristic_beg_columns, CharacterVector characteristic_end_columns, int gap_threshold, bool keep_all_periods);
RcppExport SEXP _customerRelationship_merge_relationship_periods(SEXP dtableSEXP, SEXP id_columnSEXP, SEXP from_columnSEXP, SEXP to_columnSEXP, SEXP characteristic_beg_columnsSEXP, SEXP characteristic_end_columnsSEXP, SEXP gap_thresholdSEXP, SEXP keep_all_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dtable(dtableSEXP);
    Rcpp::traits::input_parameter< std::string >::type id_column(id_columnSEXP);
    Rcpp::traits::input_parameter< std::string >::type from_column(from_columnSEXP);
    Rcpp::traits::input_parameter< std::string >::type to_column(to_columnSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type characteristic_beg_columns(characteristic_beg_columnsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type characteristic_end_columns(characteristic_end_columnsSEXP);
    Rcpp::traits::input_parameter< int >::type gap_threshold(gap_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_all_periods(keep_all_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(merge_relationship_periods(dtable, id_column, from_column, to_column, characteristic_beg_columns, characteristic_end_columns, gap_threshold, keep_all_periods));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_customerRelationship_merge_relationship_periods", (DL_FUNC) &_customerRelationship_merge_relationship_periods, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_customerRelationship(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
