# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Merge Customer Relationship Periods
#'
#' C++ implementation for merging consecutive customer relationship periods.
#' Groups records by customer ID and merges consecutive periods if the gap
#' between them is 1 day or less.
#'
#' @param dtable A DataFrame with customer relationship records
#' @param id_column Name of the ID column
#' @param from_column Name of the From date column
#' @param to_column Name of the To date column
#' @param characteristic_beg_columns Character vector of column names that preserve beginning values
#' @param characteristic_end_columns Character vector of column names that take ending values
#' @return DataFrame with merged periods and gap calculations
#'
#' @keywords internal
merge_relationship_periods <- function(dtable, id_column, from_column, to_column, characteristic_beg_columns, characteristic_end_columns) {
    .Call(`_customerRelationship_merge_relationship_periods`, dtable, id_column, from_column, to_column, characteristic_beg_columns, characteristic_end_columns)
}

